### ISSUE TITLE
Does Turtle Faucet supports TurtleCoin GUI Wallet?

### ISSUE THREAD

**Issue by fox123me** [krruzic/TurtleFaucet#2]
About the Turtle Faucet. It would seem doesn't work with Turtlecoin GUI Wallet.
Is there a way to solve the problem?
Thank you.

**Comment by oberwager** [comment]
The faucet sends TRTL to your address, the GUI wallet is a way to view your balance. They do not interact directly, and it has no affect. Your GUI wallet might not be synced or you have some other problem. Go to to help channel in the turtle-coin discord

**Comment by fox123me** [comment]
Okay! Thank you for replying so promptly.
